# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/RAMB4_S4_S16/RAMB4_S4_S16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAMB4_S4_S16 || ORIG_REF_NAME==RAMB4_S4_S16}]

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# XDC: ip/RAMB4_S4_S16/RAMB4_S4_S16_ooc.xdc

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
