# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath E:/modeltech64_10.1c/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.cache/wt [current_project]
set_property parent.project_path H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/RAMB4_S4_S16/RAMB4_S4_S16.xci
set_property used_in_simulation 1 [get_files -all H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/RAMB4_S4_S16/synth/RAMB4_S4_S16.vhd]
set_property used_in_implementation false [get_files -all h:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/RAMB4_S4_S16/RAMB4_S4_S16_ooc.xdc]
set_property is_locked true [get_files H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/RAMB4_S4_S16/RAMB4_S4_S16.xci]

read_ip -quiet h:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all h:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files h:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_verilog -library xil_defaultlib {
  H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/new/fifoctlr_icmw1.v
  H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/new/muxor.v
  H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/new/xor4.v
  H:/git/Asynchronous-FIFO/Asynchronous-FIFO/Asynchronous-FIFO.srcs/sources_1/new/xor5.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fifoctlr_icmw1 -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef fifoctlr_icmw1.dcp

catch { report_utilization -file fifoctlr_icmw1_utilization_synth.rpt -pb fifoctlr_icmw1_utilization_synth.pb }
